name: 'CD Trigger Action'
description: 'Trigger for CD'
author: 'infra <bp-deployer@github.com>'
inputs:
  application:
    required: true
    description: 'application name'
  profile:
    required: true
    description: 'available profile: dev, stage, prod'
  image-tag:
    required: true
    description: 'docker image tag to deploy'
  version:
    required: true
    description: 'version tag'
  env:
    required: false
    description: 'target environment'
  commit-sha: 
    required: false
    description: 'Commit SHA from the repository'
  repo-url:
    required: false
    description: 'Repository URL without "https://" prefix'
runs:
  using: 'Node16'
  main: 'dist/index.js'
