name: 'CD Trigger Action'
description: 'Trigger for CD'
author: 'zezaeoh <zezaeoh@github.com>'
inputs:
  application:
    required: true
    description: 'application name'
  profile:
    required: true
    description: 'available profile: dev, stage, prod'
  image-tag:
    required: true
    description: 'docker image tag to deploy'
  version:
    required: true
    description: 'version tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
