name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      # Set up Node.js
      - name: Set up Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install
      - run: |
          npm run all
